#application: wizardry-tournament
#version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /orderReport
  script: main.app

- url: /.*
  script: main.app

skip_files:
- static/audio/.*
- drafts/.*
- scripts/.*
- ^(.*/)+\.svn/.* 
- .*\.pyc 
- .*\.swp
